import { Mission, Achievement } from "@/types";

export const DAILY_MISSIONS: Mission[] = [
  {
    id: "daily-study-30",
    title: "Study for 30 Minutes",
    titleBn: "৩০ মিনিট পড়াশোনা করো",
    description: "Complete at least 30 minutes of focused study today",
    type: "daily",
    icon: "📚",
    xpReward: 100,
    coinReward: 20,
    requirement: 30,
    progress: 0,
    isCompleted: false,
  },
  {
    id: "daily-quiz-3",
    title: "Complete 3 Quizzes",
    titleBn: "৩টি কুইজ সম্পন্ন করো",
    description: "Take 3 quizzes in any subject",
    type: "daily",
    icon: "❓",
    xpReward: 80,
    coinReward: 15,
    requirement: 3,
    progress: 0,
    isCompleted: false,
  },
  {
    id: "daily-lesson-2",
    title: "Finish 2 Lessons",
    titleBn: "২টি পাঠ শেষ করো",
    description: "Complete 2 lessons from any chapter",
    type: "daily",
    icon: "✅",
    xpReward: 60,
    coinReward: 10,
    requirement: 2,
    progress: 0,
    isCompleted: false,
  },
  {
    id: "daily-streak",
    title: "Maintain Streak",
    titleBn: "স্ট্রিক বজায় রাখো",
    description: "Log in and study today to keep your streak alive",
    type: "daily",
    icon: "🔥",
    xpReward: 50,
    coinReward: 10,
    requirement: 1,
    progress: 0,
    isCompleted: false,
  },
  {
    id: "daily-perfect-quiz",
    title: "Perfect Score",
    titleBn: "পারফেক্ট স্কোর",
    description: "Get 100% on any quiz",
    type: "daily",
    icon: "⭐",
    xpReward: 150,
    coinReward: 30,
    requirement: 1,
    progress: 0,
    isCompleted: false,
  },
];

export const WEEKLY_MISSIONS: Mission[] = [
  {
    id: "weekly-study-300",
    title: "Study 5 Hours This Week",
    titleBn: "এই সপ্তাহে ৫ ঘণ্টা পড়াশোনা",
    description: "Accumulate 300 minutes of study time this week",
    type: "weekly",
    icon: "⏱️",
    xpReward: 500,
    coinReward: 100,
    requirement: 300,
    progress: 0,
    isCompleted: false,
  },
  {
    id: "weekly-subjects-3",
    title: "Study 3 Subjects",
    titleBn: "৩টি বিষয় পড়ো",
    description: "Study at least 3 different subjects this week",
    type: "weekly",
    icon: "📗",
    xpReward: 300,
    coinReward: 60,
    requirement: 3,
    progress: 0,
    isCompleted: false,
  },
  {
    id: "weekly-streak-7",
    title: "7-Day Streak",
    titleBn: "৭ দিনের স্ট্রিক",
    description: "Study every day for 7 consecutive days",
    type: "weekly",
    icon: "🔥",
    xpReward: 700,
    coinReward: 150,
    requirement: 7,
    progress: 0,
    isCompleted: false,
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "first-login",
    title: "Welcome Scholar!",
    titleBn: "স্বাগতম পণ্ডিত!",
    description: "Log in for the first time",
    icon: "🎓",
    rarity: "common",
    xpReward: 50,
    isUnlocked: false,
  },
  {
    id: "first-quiz",
    title: "Quiz Novice",
    titleBn: "কুইজ নবিশ",
    description: "Complete your first quiz",
    icon: "❓",
    rarity: "common",
    xpReward: 100,
    isUnlocked: false,
  },
  {
    id: "streak-7",
    title: "Week Warrior",
    titleBn: "সপ্তাহের যোদ্ধা",
    description: "Maintain a 7-day study streak",
    icon: "🔥",
    rarity: "rare",
    xpReward: 300,
    isUnlocked: false,
  },
  {
    id: "streak-30",
    title: "Unstoppable",
    titleBn: "অদম্য",
    description: "Maintain a 30-day study streak",
    icon: "⚡",
    rarity: "epic",
    xpReward: 1000,
    isUnlocked: false,
  },
  {
    id: "level-10",
    title: "Rising Star",
    titleBn: "উদীয়মান তারা",
    description: "Reach Level 10",
    icon: "⭐",
    rarity: "rare",
    xpReward: 500,
    isUnlocked: false,
  },
  {
    id: "level-50",
    title: "Legend",
    titleBn: "কিংবদন্তি",
    description: "Reach Level 50",
    icon: "👑",
    rarity: "legendary",
    xpReward: 5000,
    isUnlocked: false,
  },
  {
    id: "perfect-score",
    title: "Perfectionist",
    titleBn: "নিখুঁত",
    description: "Get 100% on a quiz",
    icon: "💯",
    rarity: "rare",
    xpReward: 200,
    isUnlocked: false,
  },
  {
    id: "complete-subject",
    title: "Subject Master",
    titleBn: "বিষয় মাস্টার",
    description: "Complete all chapters in a subject",
    icon: "🏆",
    rarity: "epic",
    xpReward: 1500,
    isUnlocked: false,
  },
];
